import path from "path"
import {Glob, write} from "bun"

;(async () => {
  const glob = new Glob("./res/flags/*.svg")
  const files = await Array.fromAsync(glob.scan())
  const flags = files.map(file => path.basename(file, ".svg"))
  const output = path.resolve("./src/utils/flags.ts")

  await write(
    output,
    `// Generated by npm run flags:build\nexport const FLAGS = [\n${flags.map(f => `  '${f}',\n`).join("")}]\n`,
  )
})()
